### ISSUE TITLE
Pressing down command key on macos somehow brokes other key presses

### ISSUE THREAD

**Issue by mosmetro** [floooh/sokol#794] opened 2023-02-17 12:42 UTC
For example, press arrow key and while it is being pressed, press command key. Instead of recieving SAPP_EVENTTYPE_KEY_DOWN for arrow key, we now also receive SAPP_EVENTTYPE_KEY_UP for that arrow key. That looks wrong.
Easy reproducible with pacman.c.

**Comment by floooh** [comment] 2023-02-17 17:12
Yes, I can reproduce. Looks weird, I'll start to investigate.

Funny thing is, it happens both in the native macOS version and the WASM version: https://floooh.github.io/sokol-html5/events-sapp.html

...but both have completely different input handling code... I wonder if those events are coming like that from macOS...

**Comment by floooh** [comment] 2023-02-17 17:18
Right, it's this "workaround" for even worse behaviour:

https://github.com/floooh/sokol/blob/1b9b047099a249281112262259135fe699e36342/sokol_app.h#L4180-L4189

This is the associated commit:

https://github.com/floooh/sokol/commit/55826d7a686e79eaf14c9ed1d99cb595617976c0

I'll check if that workaround is still needed...

**Comment by floooh** [comment] 2023-02-17 17:23
Ok, the workaround is still needed, but it was intended for a slightly different situation:

When you press Cmd and any key, and then keep the Cmd key pressed but release the other key, you won't get a key up event which then causes the key to remain stuck forever.

**Comment by floooh** [comment] 2023-02-17 17:27
Lots of hits when googling for this problem, I'll see if there's some better workaround recommendations among those:

- https://github.com/flutter/flutter/issues/38076
- https://bugzilla.mozilla.org/show_bug.cgi?id=1299553
- https://stackoverflow.com/questions/16604056/nsresponder-not-receiving-keyup-event-when-cmd-key-held-down
- https://stackoverflow.com/questions/25438608/javascript-keyup-isnt-called-when-command-and-another-is-pressed
- https://stackoverflow.com/questions/27380018/when-cmd-key-is-kept-pressed-keyup-is-not-triggered-for-any-other-key

**Comment by floooh** [comment] 2023-02-17 17:36
...hmm, no solutions there either, the Flutter and Firefox tickets have gone stale without fix. I don't think there's a much better workaround for this then just immediately sending a key up event to make sure the key won't get stuck. The more complicated option would be to send the key-up when the Cmd-key is released, but this would be just as confusing (because the arrow key would appear to be pressed even if it is physically released until the Cmd key is released).

I'll close the ticket, it's just as it is, and if can fix this behaviour in a clean way, it's Apple (but I guess the behaviour is intended for some mysterious reasons).

**Comment by floooh** [comment] 2023-02-17 17:41
OTH, in GLFW it works.

**Comment by floooh** [comment] 2023-02-17 18:30
Ok, this should now be "properly" fixed via https://github.com/floooh/sokol/commit/6e1e60dcc6ab1fafffac7ff31cb96d602db37f93

I'll update the pacman.c sources too (no solution for web builds though, the fix is only for native macOS builds).

**Closed by floooh** 2023-02-17 18:30 UTC

**Comment by floooh** [comment] 2023-02-17 18:31
PS: many thanks for the bug report btw :)

**Comment by mosmetro** [comment] 2023-02-18 00:23
Hmm, with this update small example posted on itch.io no more receiving keyboard events. That same example running on local web server (python3 -m http.server) works fine. That strange.
