### ISSUE TITLE
Rendering a simple image results in a SOKOL_ASSERT crash in _sg_mtl_copy_image_content

### ISSUE THREAD

**Issue by medvednikov** [floooh/sokol#446] opened 2020-12-29 13:10 UTC
The crash is "fixed" by commenting out the SOKOL_ASSERT in `_sg_mtl_copy_image_content`:

```
             for (int slice_index = 0; slice_index < num_slices; slice_index++) {
                 const int mtl_slice_index = (img->cmn.type == SG_IMAGETYPE_CUBE) ? face_index : slice_index;
                 const int slice_offset = slice_index * bytes_per_slice;
-                SOKOL_ASSERT((slice_offset + bytes_per_slice) <= (int)content->subimage[face_index][mip_index].size);
+//                SOKOL_ASSERT((slice_offset + bytes_per_slice) <= (int)content->subimage[face_index][mip_index].size);
```

After this fix the image is rendered fine.

This is Metal, macOS.

Here's the image that caused this:

![background](https://user-images.githubusercontent.com/687996/103285755-49d28480-49df-11eb-8c5e-2ee66beab490.png)

It's loaded via stb_image. All other images I've tested worked fine.

It can be reproduced by installing V and running the flappy bird example:

```
git clone --depth 1 https://github.com/vlang/v
cd v
make
cd examples/flappylearning
../../v run game.v
```

**Comment by tanis2000** [comment] 2021-02-15 14:39
I'm pretty sure this issue is the same I've just hit. You should have a look at the bits per pixel returned by the `stbi_load_from_memory` function. There are good chances they are 3 instead of 4 and you're probably creating the image as a RGBA8.

The issue now is that there is no RGB8 format in Sokol. @floooh what should we do?

**Comment by floooh** [comment] 2021-02-15 15:26
I'll try to reproduce the issue next. But @tanis2000 your idea sounds plausible.

sokol_gfx.h doesn't support 3-channel pixel formats anymore because they haven't been supported everywhere and modern 3D-APIs switched away from them anyway (e.g. see WebGPU:

https://github.com/webgpu-native/webgpu-headers/blob/ec1024fc93ef5bc45c2fef75838fef88df11dfdc/webgpu.h#L336-L393

stbi_image.h can be forced to expand an RGB image to RGBA with the desired_channels parameter:

https://github.com/nothings/stb/blob/b42009b3b9d4ca35bc703f5310eedc74f584be58/stb_image.h#L146

For instance in the loadpng-sapp.c sample:

https://github.com/floooh/sokol-samples/blob/8ffca145939f65b95543d6b07f5b8f058994c3b9/sapp/loadpng-sapp.c#L158-L163

**Comment by tanis2000** [comment] 2021-02-15 15:43
Yes, I have been following stb's way too. There is a constant for RGBA8 that you can pass for the desired number of channels: `STBI_rgb_alpha`.

According to the OP the issue comes from this line: https://github.com/vlang/v/blob/fe007f9b160f9d685df14851d7d239461d6b6b29/examples/flappylearning/game.v#L225

which in turn leads to the underlying library which is using the number of bits per pixel returned by stbi: https://github.com/vlang/v/blob/d08a0b5a7ca2077197ad8ea2d02870610f10a42d/vlib/gg/image.v#L53

So my theory holds. It's actually a problem in the implementation of v's gg library

**Comment by floooh** [comment] 2021-02-15 17:43
Yep confirmed, the image file has 3 channels, and trying to feed that into an SG_PIXELFORMAT_RGBA8 texture produces the above assertion (rightfully).

Plugging the texture into the [loadpng-sapp sample](https://github.com/floooh/sokol-samples/blob/master/sapp/loadpng-sapp.c) works (because this calls stbi_load_from_memory() with ```desired_channels=4``` so that stb_image.h expands the 3-bytes-per-pixel data to 4-bytes-per-pixel.

You also need to ignore the value that's returned in ```num_channels```, because this will be set to 3 (the number of channels in the original image).

Closing the ticket, as the fix is outside of sokol_gfx.h

**Closed by floooh** 2021-02-15 17:43 UTC
Labels: bug

**Comment by medvednikov** [comment] 2021-03-15 22:27
Thanks, @tanis2000  and @floooh

**Comment by medvednikov** [comment] 2021-03-15 22:38
I fixed it by ignoring the value that's returned by stb_image.
