### ISSUE TITLE
Problem with creating cube render target image with multisampling for D3D backend 

### ISSUE THREAD

**Issue by ilar81** [floooh/sokol#137] opened 2019-04-01 14:35 UTC
Hello. May be I've found out new issue. When I've tried to create cubemap rendertarget with such description structure:
sg_image_desc cube_img_desc = {
		.type = SG_IMAGETYPE_CUBE,
		.render_target = true,
		.width = 512,
		.height = 512,
		.min_filter = SG_FILTER_LINEAR,
		.mag_filter = SG_FILTER_LINEAR,
		.sample_count = 4,
	};
the program was crashed for Direct3D backend. For OpenGL backend all worked fine. Experimenting with it I've found out that it working fine with 'sample_count = 1'.  This is issue or I make something wrong?

**Comment by floooh** [comment] 2019-04-01 14:56
Hi, it's most likely a bug in sokol_gfx.h, because I haven't written a test/sample for that case yet.

I'll write a sample like this: http://floooh.github.io/oryol/asmjs/RenderToCubeMap.html and see if I can reproduce the issue.

Could you still post the code of how the sg_pass_desc structs look like, and the 'render loop'? (there should be 6 pass obects, one for each cubemap face, and 6 separate render passes).

Thanks for the bug report!

**Comment by ilar81** [comment] 2019-04-01 17:07
I guess all source code is useless, cause I'll post the most important fragment only:
sg_image_desc cube_img_desc = {
		.type = SG_IMAGETYPE_CUBE,
		.render_target = true,
		.width = 512,
		.height = 512,
		.min_filter = SG_FILTER_LINEAR,
		.mag_filter = SG_FILTER_LINEAR,
		.sample_count = 1,
	};
	sg_image color_cube_img = sg_make_image(&cube_img_desc);
	cube_img_desc.pixel_format = SG_PIXELFORMAT_DEPTH;
	sg_image depth_cube_img = sg_make_image(&cube_img_desc);
	
	sg_pass offscreen_cube_passes[6];
	for (int i = 0; i < 6; i++) {
		offscreen_cube_passes[i] = sg_make_pass(&(sg_pass_desc) {
			.color_attachments[0] = {
				.image = color_cube_img,
				.face = i
			},
			.depth_stencil_attachment = {
				.image = depth_cube_img,
				.face = i
			}
		});
	}
	
	......
	
	hmm_vec3 targets[6] = {
		HMM_Vec3(1.0f, 0.0f, 0.0f),
		HMM_Vec3(-1.0f, 0.0f, 0.0f),
		HMM_Vec3(0.0f, 1.0f, 0.0f),
		HMM_Vec3(0.0f, -1.0f, 0.0f),
		HMM_Vec3(0.0f, 0.0f, 1.0f),
		HMM_Vec3(0.0f, 0.0f, -1.0f),
	};

	hmm_vec3 ups[6] = {
		HMM_Vec3(0.0f, -1.0f, 0.0f),
		HMM_Vec3(0.0f, -1.0f, 0.0f),
		HMM_Vec3(0.0f, 0.0f, 1.0f),
		HMM_Vec3(0.0f, 0.0f, -1.0f),
		HMM_Vec3(0.0f, -1.0f, 0.0f),
		HMM_Vec3(0.0f, -1.0f, 0.0f),
	};
	
	......
	
	hmm_vec3 eye_vec = HMM_Vec3(0.0f, 1.5f, 6.0f);
	
	hmm_mat4 cube_proj = HMM_Perspective(90.0f, 1.f, 0.01f, 10.0f);
	
	 while (d3d11_process_events()) {
		rx += 1.0f; ry += 2.0f;
		hmm_mat4 model = HMM_MultiplyMat4(
            HMM_Rotate(rx, HMM_Vec3(1.0f, 0.0f, 0.0f)),
            HMM_Rotate(ry, HMM_Vec3(0.0f, 1.0f, 0.0f)));
		for (int i = 0; i < 6; i++) {
			hmm_vec3 target_vec = HMM_AddVec3(eye_vec, targets[i]);
			hmm_mat4 cube_view = HMM_LookAt(eye_vec, target_vec, ups[i]);
			hmm_mat4 cube_view_proj = HMM_MultiplyMat4(cube_proj, cube_view);
			vs_params.mvp = HMM_MultiplyMat4(cube_view_proj, model);
			sg_begin_pass(offscreen_cube_passes[i], &offscreen_pass_action);
			sg_apply_pipeline(offscreen_pip);
			sg_apply_bindings(&offscreen_bind);
			sg_apply_uniforms(SG_SHADERSTAGE_VS, 0, &vs_params, sizeof(vs_params));
			sg_draw(0, 36, 1);
			sg_end_pass();
		}
		......
	 }

**Comment by floooh** [comment] 2019-04-01 17:43
...hmm... I would have used a normal 2D render target image for the depth buffer and reused that in all passes, but I guess that isn't the problem.

I'll try to write a little sample tomorrow to reproduce the problem.

**Comment by ilar81** [comment] 2019-04-02 12:31
I've experimented further and found out that problem is located in code where MSAA texture is created(hr is fault): 
if (img->sample_count > 1) {
		d3d11_tex_desc.BindFlags |= D3D11_BIND_RENDER_TARGET;
                d3d11_tex_desc.SampleDesc.Count = img->sample_count;
                d3d11_tex_desc.SampleDesc.Quality = (UINT)D3D11_STANDARD_MULTISAMPLE_PATTERN;
                hr = ID3D11Device_CreateTexture2D(_sg.d3d11.dev, &d3d11_tex_desc, NULL, &img->d3d11_texmsaa);
                SOKOL_ASSERT(SUCCEEDED(hr) && img->d3d11_texmsaa);
            }
I've experimented with adding in this condition d3d11_tex_desc.MiscFlags = 0 and all worked. I guess that problem can be solved this way: 6 separated MSAA textures are needed for cubemap instead of one MSAA cubemap.

**Comment by floooh** [comment] 2019-04-02 13:12
Hmm, yeah. When I'm trying to create a multisamples cube-texture in the Oryol sample there's a pretty clear error message from D3D11 in the debug console "ID3D11Device::CreateTexture2D: Cubemaps do not support multisampling! You must set SampleDesc.Count (...) to 1...".

I'll also see what it looks like on Metal. But as you're saying, the proper solution is to create 6 separate MSAA render-target textures, and those need to be resolved to the cubemap texture in sg_end_pass().

**Comment by floooh** [comment] 2019-04-02 13:35
...yep, Metal doesn't allow multi-sampled cube-maps either, in any version and on any GPU.

...actually, only one 2D MSAA render target texture is needed, not six (I just checked, and that's how I implemented the GL backend, even though that works basically by accident).

Basically, an MSAA cubemap rendertarget sg_image would contain a regular cubemap texture, and a single 2D MSAA rendertarget texture the size of one cubemap face. A render pass renders to that internal MSAA texture, and resolves it to the right cubemap face in sg_end_pass().

Ok, that sounds like a plan. Might take a couple of days because I need to fix both the D3D and Metal backend, and write that test/example program.

**Comment by floooh** [comment] 2019-04-07 20:38
...just a small update, this turned out to be quite the rabbit hole :) On Mac, MSAA-resolve to cubemap faces other than the first face seems to be broken (both in Metal and GL). The Google Dawn team has stumbled over the same problem recently: https://twitter.com/DaKangz/status/1114495528191045632

I'll do the D3D11 fix in the next few days, not expecting any problems there. The WIP sokol-samples is here: https://github.com/floooh/sokol-samples/blob/master/sapp/cubemaprt-sapp.c

**Comment by floooh** [comment] 2019-04-08 14:20
There's now a fix for D3D11 in commit 82346ae0365a3b1157e2ddce591a2d01087316a1.

I'll keep the ticket open until I investigated the various macOS problems more.

**Comment by ilar81** [comment] 2019-04-08 18:20
I've tested D3D11 version. It works very well. Thanks.

**Comment by floooh** [comment] 2019-04-10 21:55
Ok, some more notes for myself:

iOS behaves correct both on Metal and GLES3, so it's definitely a macOS problem. I filed a bug on Apple's bugtracker with "problemID=49770367".

Closing this ticket now since there's no useful way to workaround the bug.

**Closed by floooh** 2019-04-10 21:55 UTC
Labels: bug
