### ISSUE TITLE
sokol_app.h: key mapping inconsistency between html5 & win32 implementations

### ISSUE THREAD

**Issue by C6H8O7** [floooh/sokol#227] opened 2019-10-28 22:31 UTC
Hi !

I'm using an AZERTY keyboard :
- On windows, when pressing A key I get the Q event (fair enough if we consider the US QWERTY layout to be the reference).
- However, when pressing A key on browser, I get the A event, which create inconsistency between windows port and html5 port.

Following [emscripten's documentation](https://emscripten.org/docs/api_reference/html5.h.html), "code" value of event should be "layout-proof", e.g. when pressing A on AZERTY keyboard on html5 : `code="KeyQ" key="a"`

I guess both choices here are either to make everything "based on US QWERTY layout" or to make everything returning local layout.
I don't know what's your thought on that, and I didn't test it on other platforms so I don't know what is the general approach on this.

(By the way, thanks for sharing such libraries, they come in very handy !)

**Comment by floooh** [comment] 2019-10-29 09:57
Hi, yes... I was somewhat expecting that the HTML5 keyboard handling would show problems in some situations. Currently I'm using the ```keyCode``` member (https://emscripten.org/docs/api_reference/html5.h.html#c.EmscriptenKeyboardEvent.keyCode), which is marked as deprecated but gave me simple numerical values which looked most like Windows-style virtual keycodes.

The intended behaviour would be to return the Q key (per your example), so I think the emscripten input callback must be changed to use the ```code``` member, and translate to sokol-app keycodes via string compares... which sucks a bit, but it's hardly performance-critcal ;)

...maybe I can cheat a bit and only look at the 3rd character of the returned string if all strings follow the "key..." pattern.

**Comment by C6H8O7** [comment] 2019-10-30 09:44
A table can be found [here (english page hasn't the table)](https://developer.mozilla.org/fr/docs/Web/API/KeyboardEvent/code) and the key pattern doesn't seem to be used in other circumstances than for letters.

As for using string compares, maybe a quick&basic hash could be a good solution, using something like [FNV-1a](http://www.isthe.com/chongo/tech/comp/fnv/), so we wouldn't end up strcmping every available key against event code but rather make a quick hash out of it and just compare against ints ?

**Comment by melMass** [comment] 2020-02-02 18:00
I have the same issue on OSX and an AZERTY keyboard, the keys are mapped to a qwerty layout so `SAPP_KEYCODE_Q` == A on an AZERTY keyboard.

**Comment by floooh** [comment] 2021-09-02 21:04
I just rewrote the sokol_app.h key event handling in the Emscripten backend which should address this issue. The SAPP_EVENTTYPE_KEY_DOWN and _UP events should ignore any keyboard layout mappings and should return the physical key, similar to the native platforms.

The fix is in this commit: https://github.com/floooh/sokol/commit/5c144b39e9578a1e5dad0f688be867f51fb5af9a

(I just used a strcmp() loop for now, not a hash lookup)

**Closed by floooh** 2021-09-02 21:04 UTC
Labels: bug
