### ISSUE TITLE
Make "buffer-less" drawing available

### ISSUE THREAD

**Issue by iOrange** [floooh/sokol#584] opened 2021-11-27 02:19 UTC
Sometimes user might want to use "buffer-less" drawing (like for fullscreen triangles and so on).
That means no vertex and index buffers, no input layout. Vertex shader generates the output using only vertex id.

Right now sg_validation* funcs will trigger if you try to do jus that.

Like this - https://www.reddit.com/r/gamedev/comments/2j17wk/a_slightly_faster_bufferless_vertex_shader_trick/

**Comment by floooh** [comment] 2021-11-27 13:43
Closing this as a duplicate of https://github.com/floooh/sokol/issues/280

The reason why this isn't supported so far is the GLES2/WebGL code path (it could either be added behind a feature flag, or at some later point when the WebGL/GLES2 code path will be dropped).

**Closed by floooh** 2021-11-27 13:43 UTC
Labels: duplicate

**Comment by floooh** [comment] 2024-04-04 18:10
This will work after the `storage-buffer` branch is merged, sample looking like this:

- C: https://github.com/floooh/sokol-samples/blob/storage-buffers/sapp/triangle-bufferless-sapp.c
- GLSL: https://github.com/floooh/sokol-samples/blob/storage-buffers/sapp/triangle-bufferless-sapp.glsl
