### ISSUE TITLE
The WebGL renderer does not produce the same output as the GLES renderer after updating to samplers.

### ISSUE THREAD

**Issue by caiiiycuk** [floooh/sokol#996] opened 2024-02-22 20:27 UTC
Hi, I am a member of a team that is porting a D3D renderer of Perimeter to Sokol. We are doing this in our free time, so it has taken a while. We started before Sokol had samplers. A couple of days ago, we updated our Sokol to the latest version, and everything was smooth, except for WebGL.

The WebGL renderer does not produce the same output as the GLES renderer on Linux. This is a bit strange; we didn't change anything, just split the shaders to use samplers. We have two objects that are rendered incorrectly in WebGL: an energy shield (the blue one) and chaos (fog outside of the terrain).

GLES3/WebGL without samplers:
![wo-sampler](https://github.com/floooh/sokol/assets/1727152/fa4f609c-8de0-4537-a9f0-1ef184f699af)

WebGL with samplers:
![with-samplers](https://github.com/floooh/sokol/assets/1727152/6403687a-3fda-46da-9786-98a952313ee0)

Same picture in FF, Chrome, none WebGL warnings.

The chaos is just black, and the shield should be blue and is actually visible but too transparent. The shader used to render these objects is also used for many other objects and seems to work fine. Unfortunately, we have no idea what could be going wrong, maybe some internal state of Sokol. It could certainly be an issue with our renderer code, but why then does it work fine on Linux with GLES and the only problem is with WebGL?

Anyway, maybe you have some ideas for tests.

I did a bisect, and the first bad commit that I was able to build is:

- sokol: facd53fdf15b5d893bcefd98f613d3ed27375215
- tools-bin: 6040b18d39649d56dbae2ae1aed59fb755b26369

Here is the shader code (very simple):

Without samplers: 
[shader.txt](https://github.com/floooh/sokol/files/14379022/shader.txt)

With samplers:
[shader2.txt](https://github.com/floooh/sokol/files/14379036/shader2.txt)

Note: In shader2.txt, we use one sampler for two textures. I'm not sure if this is valid, but we also tried using two samplers for two textures with no differences.

**Comment by floooh** [comment] 2024-02-23 09:09
Strange indeed. I'll set aside some time over the next few days to look at the problem.

Is there some way I can test the WebGL build myself? (e.g. is is hosted somewhere?)

**Comment by floooh** [comment] 2024-02-23 16:20
Btw in the latest demo link you provided (with the Imgui-Integration) I'm seeing the fog (in Chrome on macOS):

<img width="1510" alt="image" src="https://github.com/floooh/sokol/assets/1699414/992f51f0-e3d3-4ca9-b635-e73f68bb3bf1">

Did you update sokol_gfx.h since the time those textures showed up as black? As I wrote on Twitter, until end of Oct-2023 there was a bug in the GL backend which caused textures without mipmaps to render as black/transparent if they used a sampler with a `.mipmap_filter` != `SG_FILTER_NONE`. WebGL may be especially strict about this, while native GL implementations may be more forgiving there.

But this had been fixed in the meantime.

How can I best check the energy shield?

**Comment by floooh** [comment] 2024-02-23 16:30
PS: once we figured out that texturing problem we should do something about the many create/destroy buffer calls per frame, and that each sg_draw() is accompanied by a viewport, scissor-rect, pipeline and bindings-update (is possible) :)

**Comment by floooh** [comment] 2024-02-23 16:37
Hmm, I also see the fog though on the non-imgui build with samplers (where it should be black).

**Comment by caiiiycuk** [comment] 2024-02-24 07:52
Oh, that's true; it works! I didn't test it on different OSes, and so I thought it was just broken. But now, after more testing, we can say that it works everywhere except on Windows. I also tried setting `.mipmap_filter` to `SG_FILTER_NONE` - it didn't help.

![изображение](https://github.com/floooh/sokol/assets/1727152/9fa7faee-c7b3-48e2-bc87-0805581665c2)

**Does not work** (both chaos and shield):
- Windows 11 Chrome 122.0.0.0 ANGLE (NVIDIA, NVIDIA GeForce RTX 3050 Laptop GPU (0x000025A2) Direct3D11 vs_5_0 ps_5_0, D3D11)
- Windows 11 Firefox 123.0 ANGLE (AMD, Radeon HD 3200 Graphics Direct3D11 vs_5_0 ps_5_0), or similar
- Windows 10 + RTX 2070 on FF
- Windows + Intel GPU

Works fine:
- Ubuntu 23.10 + Intel
- linux + firefox + AMD Ryzen 7700 igpu
- Mac M1 Firefox / Chrome
- MacBook Pro 13 Iris GPU Chrome

Regarding shield:

Just start a **Battle** game instead of a campaign, then place the energy core and activate the shield.
![изображение](https://github.com/floooh/sokol/assets/1727152/e3005509-2eaa-485c-bdf5-f8d729089b89)

**Comment by caiiiycuk** [comment] 2024-02-24 08:04
Also natively it works fine:
- windows native GL on Wine and real windows
- gles3 on unbuntu under wsl

**Comment by floooh** [comment] 2024-02-24 11:33
Ok, I have a Windows PC with RTX2070 and a Windows laptop with Intel GPU, should be close enough to reproduce.

It almost looks like a D3D11 limitation I'm not aware of yet.

**Comment by caiiiycuk** [comment] 2024-02-24 11:54
This is commit that introduced this bug in game https://github.com/KD-lab-Open-Source/Perimeter/commit/e06f09ca458322718dcf3f0554f5610aec5afa48

**Comment by IonAgorria** [comment] 2024-02-24 12:59
Currently im trying to compile it with sokol enabled for D3D11, will report back once it works

**Comment by floooh** [comment] 2024-02-24 13:19
One obvious difference I see is here when creating a sampler object:

```
    sampler_desc.min_filter = SG_FILTER_LINEAR;
    sampler_desc.mag_filter = SG_FILTER_LINEAR;
    sampler_desc.mipmap_filter = SG_FILTER_LINEAR;
```

...this is different from this old code:

```
imgdesc->min_filter = imgdesc->mag_filter = SG_FILTER_NEAREST;
```

...the equivalent would be:

```
    sampler_desc.min_filter = SG_FILTER_NEAREST;
    sampler_desc.mag_filter = SG_FILTER_NEAREST;
    sampler_desc.mipmap_filter = SG_FILTER_NONE;
```

Nearest vs Linear shouldn't result in the such a rendering artefact though, and @caiiiycuk already confirmend that changing the mipmap filter doesn't make a difference, and D3D11 doesn't have an actual 'none' mipmap filter mode anyway, only 'point' (aka nearest) or 'linear'.

**Comment by floooh** [comment] 2024-02-25 16:28
...not much new from my side today except that I see the error on my Windows laptop too.

So we definitely have a case where WebGL behaves differently between platforms, which is very unusual.

Do you guys know what those two textures are which are affected, and what could be special about them? Things like "non-power-of-2" - although that shouldn't matter anymore on WebGL2. But there must be a reason why some textures have that problem while others work fine.

**Comment by floooh** [comment] 2024-02-25 17:29
Btw, the Sprector.js webgl debugger might come in handy, for instance here I have the drawcall selected which renders the black background. On the right side you can inspect the entire WebGL2 state at the time of the drawcall. I haven't dived in detail into the state yet though.

The extension is here: https://chromewebstore.google.com/detail/spectorjs/denbgaamihkadbghdceggmchnflmhpmk 

Here's what it looks like with the problematic draw call selected:

![perimeter_spectre](https://github.com/floooh/sokol/assets/1699414/9b218df6-1cc4-42a7-b9fb-edb5b38116d9)

**Comment by floooh** [comment] 2024-02-25 17:32
Btw, when I look very closely on my Intel GPU laptop I actually see some moving "cloud structures" in the black area, so it's not completely black, just extremely dark... hmm.

**Comment by caiiiycuk** [comment] 2024-02-25 18:18
Yeah, and shield also sometimes visible it just  too much transparent. The chaos (fog) render is very simple, it just two cloud textures that moving by translation matrix. Maybe there is some browser bug with loading webp image (faced this once on iphone safari). Probably I can try to extract this into simple test case.

**Comment by caiiiycuk** [comment] 2024-02-25 18:21
I mean tex coordinates changing each frame, vertexes are stable

**Comment by caiiiycuk** [comment] 2024-02-26 19:27
Luckily, when @IonAgorria added support for D3D11, he removed the `glsl100` dialect from the list of supported dialects. After that, rendering started to work fine. There is probably a bug in sokol-tools-bin that generates code to load glsl100 shaders in a GLES3 environment.

![___ _____](https://github.com/floooh/sokol/assets/1727152/552ab249-1c01-4014-9cc0-7a1381e099ed)

Here is a zip with shaders `glsl330:glsl300es:metal_macos` and `"glsl330:glsl100:glsl300es:metal_macos`.

[shaders.zip](https://github.com/floooh/sokol/files/14409887/shaders.zip)

**Comment by caiiiycuk** [comment] 2024-02-27 17:35
Of course. Supporting GLSL100 seems unnecessary, but could there be an error in the Sokol tool? It appears there are two blocks defined with `#if defined(SOKOL_GLES3)`, where one block uses GLSL100 code and the other uses GLSL300es. Is that correct?

**Comment by floooh** [comment] 2024-02-28 09:48
Theoretically it makes sense from the standpoint that GLSL100 shaders should also work in GLES3/WebGL2 (which for the most part they do, but as you discovered apparently not always). I'm not sure if sokol-shdc does the right thing when *both* glsl100 and glsl300es output is created, but in any case it makes more sense to remove glsl100 output from sokol-shdc entirely.

**Closed** 2024-02-28 09:48 UTC
Labels: bug
