### ISSUE TITLE
sometimes, on lanch an executable file could not get window focus

### ISSUE THREAD

**Issue by dazkzi** [floooh/sokol#757] opened 2022-12-07 11:10 UTC
on mac，open an executable file, in the meantime move the mouse，the new window will not get focus

this will not happen when using sdl2 or glfw

**Comment by floooh** [comment] 2022-12-07 17:41
Do you build the executable as a command line application, or as a an application bundle? I seem to remember that I have seen this behaviour with command line builds, but not with regular applications.

Also, if you already build as app bundle, what does your .plist config file look like?

**Comment by dazkzi** [comment] 2022-12-08 03:29
This only occurs on the command line executable, the bundle is fine.

GLFW and SDL2 are working fine when start the executable from command line.

**Comment by floooh** [comment] 2022-12-08 09:30
Ok, I'll try to find out what GLFW does differently on startup than sokol_app.h, it might be some attribute that's normally provided by the .plist file but needs to be set programmatically otherwise.

**Comment by floooh** [comment] 2023-01-15 14:16
Hmm, I can't seem to reproduce the issue here. I'm compiling the events-sapp.c sample as cmdline app (not as app bundle), and the window has focus right from the start (e.g. just moving the mouse reports mouse events to the app).

Can you help me reproduce the issue? For instance, what macOS and Xcode version are you on? (I'm on macOS Ventura 13.1 and Xcode 14.0.1).

**Comment by dazkzi** [comment] 2023-02-17 15:34
I found that if it takes too much time in init, this thing will happen. Such as add this empty loop in init.
```
for (int i = 0; i < 50000; i++) {
    printf("zzzzz\n");
}
```

**Comment by floooh** [comment] 2023-02-17 16:43
Hmm, good information. Still weird though because there's nothing special about the init callback, it's just called in the first frame before the frame callback. All application- and window-system setup has already happened at that time.

I also checked GLFW, and sokol_app.h is already doing the same things (but I remember that I had this sort of problem before adding the "ActivationPolicy" setting. It basically comes down to these 3 things:

https://github.com/floooh/sokol/blob/1b9b047099a249281112262259135fe699e36342/sokol_app.h#L3831-L3833

**Comment by floooh** [comment] 2024-01-31 14:15
Apparently fixed via #982, although I was unable to reproduce the original issue on my M1 Mac with macOS 14.3 (e.g. Apple might have fixed it too?).

**Closed by floooh** 2024-01-31 14:15 UTC
Labels: sokol-app, macos, info needed
