### ISSUE TITLE
Image flickering

### ISSUE THREAD

**Issue by caiiiycuk** [floooh/sokol#478] opened 2021-02-15 02:34 UTC
Hi. First of all I am not 100% sure that this problem is a sokol problem. I trying to fix it for a long time and I am not have any idea what is going wrong. I use simple render function that should render rgba buffer each frame. But it flickers between current and prev frame. Looks like double buffering problem. Look video:

https://user-images.githubusercontent.com/1727152/107899158-1b4d4080-6f70-11eb-898c-4b73cc2860f1.mov

The render function:
```
void sokolFrame() {
  std::lock_guard<std::mutex> g(mutex);

  if (frameWidth == 0 || frameHeight == 0 || renderedFrame == frameCount) {
    return;
  }

  if (!state || state->width != frameWidth || state->height != frameHeight) {
    delete state;

    state = new GfxState(frameWidth, frameHeight);
  }

  sg_image_content imageContent = {};
  imageContent.subimage[0][0] = {};
  imageContent.subimage[0][0].ptr = frameRgba;
  imageContent.subimage[0][0].size =
      (state->width) * (state->height) * (int)sizeof(uint32_t);

  sg_update_image(state->bind.fs_images[0], &imageContent);

  sg_begin_default_pass(&state->pass, state->width, state->height);
  sg_apply_pipeline(state->pipeline);
  sg_apply_bindings(&state->bind);
  sg_draw(0, 4, 1);
  sg_end_pass();
  sg_commit();

  renderedFrame = frameCount;
}
```

`frameRgba` - is an rgba buffer with latest frame.

The full sources of render: https://github.com/caiiiycuk/js-dos/blob/emulators/src/dos/sokol/protocol-sokol.cpp

--
OT: Is it possible to resize sapp window from code?

**Comment by floooh** [comment] 2021-02-15 09:57
I think you're leaking the vertex buffer in the GfxState destructor, but that's probably not the reason.

Only thing I can see that's suspicious is that running sokol-app plus sokol-gfx in a separate thread isn't tested. I can imaging that various window systems don't like that. Did you try what happens when you're running sokol-app and sokol-gfx on the main thread?

**Comment by caiiiycuk** [comment] 2021-02-16 02:12
I fixed memory leak, and put sapp in main thread. Same here. I even removed real frame updates, and using static frames. App started with green frame, and then it updated once to blue.

https://user-images.githubusercontent.com/1727152/108009315-08e90a80-7035-11eb-954f-f867b2c4fa22.mov

The time frame when image is flickering after frame is updated very different can be between 0.5 sec up to 4 sec, and then flickering stops and image became blue.

I tried i3wm, and gnome 3 both have same problem.I also tried sokol samples, and they works totally fine.

I have prepared minimal test case that reproduce problem.
[sokol-bug.zip](https://github.com/floooh/sokol/files/5985535/sokol-bug.zip)

I compile it with this command:
```
clang++ bug.cpp -lX11 -lXcursor -lXi -ldl -lGL -lpthread -lasound -o /tmp/bug
```

**Comment by 0x1100** [comment] 2021-02-22 06:28
Just a hunch.
Try using ```-pthread``` instead of ```-lpthread```.

https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html
```
-pthread
Define additional macros required for using the POSIX threads library.
You should use this option consistently for both compilation and linking.
This option is supported on GNU/Linux targets, most other Unix derivatives,
and also on x86 Cygwin and MinGW targets.
```
https://clang.llvm.org/docs/ClangCommandLineReference.html
```
-pthread, -no-pthread
Support POSIX threads in generated code
```

**Comment by floooh** [comment] 2021-02-22 17:36
I'll look into this issue next, at least trying to find out what's going on ;)

**Comment by floooh** [comment] 2021-02-23 16:12
I can reproduce the issue on my Ubuntu 20.04 laptop both with -lpthread and -pthread. Tinkering around with the demo code now...

**Comment by floooh** [comment] 2021-02-23 16:38
Ok, the problem is here:

```c
if (frameWidth == 0 || frameHeight == 0 || renderedFrame == frameCount) {
    return;
}
```
If you return early from the frame callback like this, without rendering a new frame, then sokol_app.h will still *present* a new frame, and this causes the flickering, because now a rendering surface becomes visible that hasn't been updated.

Basically you always need to render *something* in the frame callback, returning early without rendering into the framebuffer will cause garbage being displayed.

The whole topic is related to the discussion in this issue, which would allow "lazy rendering", e.g. stopping the display flip if no rendering update needs to happen:

https://github.com/floooh/sokol/issues/301

I hope this helps with finding a solution for your case. I'm closing the issue for now, but keep an eye on followup replies :)

**Closed by floooh** 2021-02-23 16:38 UTC

**Comment by caiiiycuk** [comment] 2021-02-24 00:23
Wow, thanks. The solution was so simple :)
