### ISSUE TITLE
[Feature Request] - Create a compiler dynamic library

### ISSUE THREAD

**Issue by rcases** [floooh/sokol#499] opened 2021-03-29 12:51 UTC
Split sokol-shdc in a dynamic library and an application  frontend for that library.
The library could allow Sokol applications play with shaders without recompile them offline.

Additional features:
* Allow use custom file reader/writer.

**Comment by floooh** [comment] 2021-03-29 16:26
The first part is a duplicate of this issue:

https://github.com/floooh/sokol-tools/issues/34

(it's essentually about creating a library API for sokol-shdc, wether the library is then compiled as static lib or DLL is then up to the user)

The second request is a lot more involved though, because it would require to expose a plugin API which would be much more verbose than just using the shader compiler as library (I think it's mainly the shader reflection data that must be exposed).

(closing this as this is a duplicate)

**Closed by floooh** 2021-03-29 16:26 UTC

**Comment by rcases** [comment] 2021-03-29 19:34
When I said custom file reader/writer, I meant define callback functions for basic file operations (open, read, write, seek, tell ,close). If not defined, use the standard ones.
More or less as [SDL_RWops](https://wiki.libsdl.org/SDL_RWops?highlight=%28%5CbCategoryStruct%5Cb%29%7C%28CategoryIO%29)

I think only a few small changes would be necessary in [input.cc](https://github.com/floooh/sokol-tools/blob/eacb50ff3deb52bf7bfbb0c7ed0860a687df20e7/src/shdc/input.cc#L12) and other minor changes in the files that generates the outputs.
And this strictly affects the input and output files. Not the temporary ones.

**Comment by floooh** [comment] 2021-03-30 11:16
> I meant define callback functions for basic file operations

Ah alright, yeah, that makes sense.

Could you maybe add a little comment to this ticket here: https://github.com/floooh/sokol-tools/issues/34, so that the idea doesn't get lost.
