### ISSUE TITLE
sokol_app.h: macOS with GLCORE33 mouse position update is noticeably laggy

### ISSUE THREAD

**Issue by slmjkdbtl** [floooh/sokol#341] opened 2020-07-21 08:58 UTC
```c
#define SOKOL_IMPL
#define SOKOL_GLCORE33
// #define SOKOL_METAL

#include "sokol_app.h"

void event(const sapp_event* e) {
	printf("%f, %f\n", e->mouse_x, e->mouse_y);
}

sapp_desc sokol_main(int argc, char* argv[]) {
	return (sapp_desc){
		.event_cb = event,
	};
}
```
toggling between `SOKOL_GLCORE33` and `SOKOL_METAL` can tell the mouse position update with `GLCORE33` is laggier, it's more obvious if drawing something at mouse position

**Comment by floooh** [comment] 2020-07-21 09:16
I don't think I can do much about that. The mouse event code is the same between Metal and GL in sokol_app.h, it might be that NSOpenGLView has more latency for presenting the framebuffer than MTKView. I'll check for any obvious things (like triple- vs double-buffering), but it's unlikely that it's something as simple as that the case.

**Comment by slmjkdbtl** [comment] 2020-07-21 18:01
`[NSEvent setMouseCoalescingEnabled:NO]` did make the mouse event reporting more frequent (the printing frequency in the example above is higher), but it still seems a little bit laggier than with `SOKOL_METAL` (there's no obvious improvement if I draw stuff at mouse position). Thanks! I'll try do more research on this topic

**Comment by slmjkdbtl** [comment] 2020-07-30 19:38
I found that if I remove the `setNeedsDisplay` in `timerFired` impl it seem to report smooth mouse motion in the `mouseMoved` event, is it possible the timer is somehow interfering with the view / event update? (Also I didn't see other windowing libs uses a `NSTimer` and `setNeedsDisplay ` for updating view, is there an alternative way I can try?)

**Comment by floooh** [comment] 2020-08-02 14:07
Hmm ok, worth a try. IFIR had to add the NSTimer code because I couldn't get the CVDisplayLink method described here to properly work after the macOS Catalina GL regressions:

https://developer.apple.com/library/archive/qa/qa1385/_index.html

**Comment by floooh** [comment] 2021-02-22 17:29
Closing this with the mouse latency improvements for macOS that had just been merged. It's still not perfect, but very noticeably better.

**Closed by floooh** 2021-02-22 17:29 UTC
Labels: sokol-app
