### ISSUE TITLE
sokol_audio.h(1273,1): error C2362: “goto dur”跳过了“%pS”的初始化操作

### ISSUE THREAD

**Issue by alittlesail** [floooh/sokol#386] opened 2020-09-22 03:10 UTC
I try it again, it also compile error, error code is C2362.
that mean local var can't not define between goto and goto flag.

code before modify:
_SOKOL_PRIVATE bool _saudio_backend_init(void) {
REFERENCE_TIME dur; // dur is define before goto
if (FAILED(CoInitializeEx(0, COINIT_MULTITHREADED))) {
SOKOL_LOG("sokol_audio wasapi: CoInitializeEx failed");
return false;
}

code after modify:
/* CoInitializeEx could have been called elsewhere already, in which
case the function returns with S_FALSE (thus it doesn't make much
sense to check the result)
*/
CoInitializeEx(0, COINIT_MULTITHREADED);

so that is nothing to do with language or textcoding

**Comment by floooh** [comment] 2020-09-22 09:05
Ah alright, that makes sense. I was confused by the "跳过了“%pS”的初始化操作".

Strange that CI didn't complain though:

https://github.com/floooh/sokol/actions/runs/262814020

I'll commit a fix quickly.

**Comment by floooh** [comment] 2020-09-22 13:58
I have committed a "blind fix" here by putting the lifetime of the ```dur``` variable inside a scope block.

https://github.com/floooh/sokol/commit/fcc33fdc81c97ec4e5473c27560379ce94917a0a

I'm still confused though because I cannot reproduce the warning (no matter the warning level).

What compiler are you seeing this warning with? I have Visual Studio 2019 (v16.7.3)

**Closed by floooh** 2020-09-22 13:58 UTC
